const mongoose = require('mongoose')

// Create Schema
const BusinessSchema = new mongoose.Schema({
    ABN: {
        type: String,
        required: true
    },
    name: {
        type: String
    },
    // needs to autogenerated in the model
    code: {
        type: String,
        required: true,
        unique: true
    },
    address: { type: mongoose.Schema.Types.ObjectId, ref: 'Address' },
});


const Business = mongoose.model('Business', BusinessSchema);

module.exports = Business;